language: scala
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update compile test package
scala:
  - 2.10.2
  - 2.10.3
  - 2.10.4
  - 2.11.0
  - 2.11.1
  - 2.11.2
  - 2.11.3
  - 2.11.4
  - 2.11.5
  - 2.11.6
jdk:
  - oraclejdk7
  - openjdk6
notifications:
  email:
    - gvojin@gmail.com
branches:
  only:
    - master
    - record-operations
matrix:
  include:
  - scala: 2.12.0
    jdk: oraclejdk8
  include:
  - scala: 2.12.1
    jdk: oraclejdk8
  include:
  - scala: 2.12.2
    jdk: oraclejdk8
  include:
  - scala: 2.12.3
    jdk: oraclejdk8
